### PR TITLE
KCL-6480 Vue.js smart links are not highlighted on the first load

### LINKED ISSUE #21: Vue.js smart links are not highlighted on the first load
### Brief bug description

When the SDK is initialized inside of the main Vue component (App.vue) using lifecycle methods (mounted, destroyed), smart links are not highlighted (there is no blue border around Kontent elements), but clicking on the element still redirects you to Kontent.

### Expected behavior

Smart links should be highlighted on the first load of Vue application as they are highlighted in React applications.

### Additional context

I investigated it a little and found out that the problem is probably [here](https://github.com/Kentico/kontent-smart-link/blob/master/src/lib/NodeSmartLinkProvider.ts#L184) in the `relevantMutations` computation condition. We used `&&` in this condition between addedNodes and removedNodes, because we mostly tested this SDK using React application and React always tries to make as many changes to DOM in one mutation as possible, that is why there are always both `removedNodes` and `addedNodes`. But as I found out today Vue separates additions and removals into separate mutations and this condition is never met.  Replacing it with something like this should fix the problem:
```
const relevantMutations = mutations.filter(
  (mutation) =>
    mutation.target instanceof Element &&
    mutation.type === 'childList' &&
    ![HighlighterElementTag, HighlighterContainerTag].includes(mutation.target.tagName) &&
    (Array.from(mutation.addedNodes).some((node) => (node as HTMLElement).tagName !== 
    HighlighterElementTag) ||
    Array.from(mutation.removedNodes).some((node) => (node as HTMLElement).tagName !== 
    HighlighterElementTag))
);
```

### PR DESCRIPTION
**Pull request by vladislavb-kentico**
### Motivation

Fixes #21

### How to test

- [ ] Test that SDK works without a problem with a React application.
- [ ] Test that SDK works without a problem with a Vue application.

You don’t have to create a new react/vue application from scratch, just use some starter project and add hardcoded smart links to it. For example, I used https://github.com/davellanedam/vue-skeleton-mvp - Connect to preview  to test smart links in Vue.

To install smart link SDK locally to your project you can use npm link command:
1. Run npm link inside of the SDK folder.
2. Run npm link @kentico/kontent-smart-link inside your project folder.

### CODE REVIEW

File: src/lib/NodeSmartLinkProvider.ts [hunk 1]
```diff
@@ -176,14 +176,25 @@ export class NodeSmartLinkProvider {
...
+      const isTargetRelevant =
         mutation.target instanceof Element &&
-        mutation.type === 'childList' &&
-        ![HighlighterElementTag, HighlighterContainerTag].includes(mutation.target.tagName) &&
-        Array.from(mutation.addedNodes).some((node) => (node as HTMLElement).tagName !== HighlighterElementTag) &&
-        Array.from(mutation.removedNodes).some((node) => (node as HTMLElement).tagName !== HighlighterElementTag)
-    );
+        ![HighlighterElementTag, HighlighterContainerTag].includes(mutation.target.tagName);
+
+      if (!isTypeRelevant && !isTargetRelevant) {
```
Comment (Neytus) [inline src/lib/NodeSmartLinkProvider.ts:185]: I believe that a `!isTypeRelevant || !isTargetRelevant` condition would be more appropriate here, as you will be able to filter out more non-relevant cases.

Comment (vladislavb-kentico) [reply src/lib/NodeSmartLinkProvider.ts]: You are right, thanks :)
